# Generated by Django 4.2.11 on 2024-03-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('clouds', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
