# Generated by Django 4.2.11 on 2024-03-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='heatindex',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='uv',
            field=models.IntegerField(default=0),
        ),
    ]
