# Generated by Django 4.2.11 on 2024-03-28 12:13

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0003_alter_weather_timestamp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='weather',
            managers=[
                ('today', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='weather',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 14, 13, 26, 413749)),
        ),
    ]
