# Generated by Django 4.2.11 on 2024-03-28 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0004_alter_weather_managers_alter_weather_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 14, 16, 29, 154)),
        ),
    ]
