# Generated by Django 4.2.11 on 2024-04-09 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0008_alter_weather_managers_alter_weather_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 14, 30, 25, 371709)),
        ),
    ]
